#!/bin/sh
ln -s  dotfiles/ackrc ~/.ackrc
ln -s  dotfiles/gitignore ~/.gitignore
ln -s  dotfiles/screen_gem ~/.screen_gem
ln -s  dotfiles/screen_rc ~/.screenrc
ln -s  dotfiles/tmux.conf ~/.tmux.conf
ln -s  dotfiles/zshrc ~/.zshrc
